name: CI

on:
  workflow_dispatch: # allows manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  GGML_NLOOP: 3
  GGML_N_THREADS: 1

jobs: 
  build:
    strategy:
      matrix:
        include:
          - name: "x86_64-cpu"
            runner: ubuntu-24.04
            arch: x86_64
            backend: cpu
            vulkan: "OFF"
          - name: "x86_64-vulkan"
            runner: ubuntu-24.04
            arch: x86_64
            backend: vulkan
            vulkan: "ON"
          - name: "aarch64-cpu"
            runner: ubuntu-24.04-arm
            arch: aarch64
            backend: cpu
            vulkan: "OFF"
          - name: "aarch64-vulkan"
            runner: ubuntu-24.04-arm
            arch: aarch64
            backend: vulkan
            vulkan: "ON"
    
    runs-on: ${{ matrix.runner }}
    name: Build ${{ matrix.name }}

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake

      - name: Vulkan Dependencies
        if: matrix.vulkan == 'ON'
        run: |
          sudo apt-get install -y libvulkan-dev glslc

      - name: Build
        id: make_build
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_RPATH='$ORIGIN' \
            -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
            -DCMAKE_SKIP_BUILD_RPATH=ON \
            -DBUILD_SHARED_LIBS=ON \
            -DLLAMA_CURL=OFF \
            -DLLAMA_STANDALONE=OFF \
            -DGGML_VULKAN=${{ matrix.vulkan }}
          cmake --build build --config Release -j $(nproc)

      - name: Collect build artifacts
        id: collect_artifacts
        run: |
          set -e
          mkdir -p artifact/build
          cp build/bin/*.so artifact/build/ || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}-${{ github.run_id }}
          path: artifact/build
